function Hd = notch_filter
%NOTCH_FILTER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.14 and DSP System Toolbox 9.16.
% Generated on: 29-Mar-2023 07:32:30

% IIR Notching filter designed using the IIRNOTCH function.

% All frequency values are in Hz.
Fs = 200;  % Sampling Frequency

Fnotch = 50;  % Notch Frequency
Q      = 35;  % Q-factor
Apass  = 3;   % Bandwidth Attenuation

BW = Fnotch/Q;

% Calculate the coefficients using the IIRNOTCHPEAK function.
[b, a] = iirnotch(Fnotch/(Fs/2), BW/(Fs/2), Apass);
Hd     = dfilt.df2(b, a);

% [EOF]
